### ISSUE TITLE
Programmatically accessing output of `imount --check`

### ISSUE THREAD

**Issue by gtback** [ralphje/imagemounter#28]
I'd like to be able to check imagemounter's dependencies and display the results differently than the current default of just printing them.

Would you be open to a PR that separates the logic of detect missing dependencies from presenting them as output?

https://github.com/ralphje/imagemounter/blob/master/imagemounter/cli/__init__.py#L6-L72

**Comment by ralphje** [comment]
Sounds awesome. I'm definitely open for such a PR.

**Comment by gtback** [comment]
Thanks, @ralphje . I'll try to get something put together within the next week or two.
