### ISSUE TITLE
Possibility to mount disks and volumes as non-root

### ISSUE THREAD

**Issue by gtback** [ralphje/imagemounter#3]
I'm trying to determine if there's a good way to use imagemounter as a non-root user. I think it might be possible by adding a mountpoint in `/etc/fstab` that allows non-root users to mount to it, and then allow passing the path to that mountpoint through the `ImageParser` constructor, through to the `Disk` constructor and `mount` method. Something similar might be necessary to mount all the Volumes on a Disk.

Does this seem reasonable? I'm happy to implement it, but wanted to make sure it was in line with the direction of the project and I wasn't missing some more obvious way to do it.

**Comment by ralphje** [comment]
I believe a `Disk` should be mountable without any root permissions (almost all disk mount methods use FUSE). However, it would  be awesome if we could figure out a way to mount volumes without root privileges. Perhaps adding a path to /etc/fstab would work. I'd be happy to accept a PR if you could manage to get this working!

**Comment by gtback** [comment]
I've looked at this a bit and I don't think it's feasible (at least without adding a lot of complexity) The `fstab` file would need to know a lot about the image being mounted (including the file system) which makes a generic solution like the one I was trying for a lot harder.
