### ISSUE TITLE
cannot mount  with -rw , always fails.

### ISSUE THREAD

**Issue by v3ss0n** [ralphje/imagemounter#37]
I had dtried using sudo and root , it dosen't work at all.
Readonly mount is fine.
I had install xmount.

**Comment by TiceDB** [comment]
Have you tried installing from source instead of using PyPI?
The issue seems te be fixed but not available on PyPI yet.

**Comment by ralphje** [comment]
It might be that eb842496e013d34ec90e869e83b53d50d9c9eb50 fixed this, and since 3.1.0 is quite old by now (2017 - yikes), this is almost certainly the case.
